# Generated by Django 5.0.6 on 2024-08-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_user", models.CharField(max_length=25)),
                ("account", models.CharField(max_length=30)),
                ("telephone", models.CharField(max_length=15, null=True)),
                ("premiun", models.BooleanField()),
            ],
        ),
    ]
